# Generated by Django 2.2.10 on 2020-06-20 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200620_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'машина', 'verbose_name_plural': 'машины'},
        ),
    ]
