# Generated by Django 2.2.10 on 2020-06-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200620_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'обзор', 'verbose_name_plural': 'обзоры'},
        ),
    ]
